name: camera_cor_destaque
description: Aplicativo que diz em voz alta o que a câmera está vendo.
publish_to: none
version: 2.0.0-dev+1

environment:
  sdk: ^3.13.0

dependencies:
  colornames: ^0.2.0
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.5
  image: ^4.10.1
  image_picker: ^1.2.3
  palette_generator: ^0.3.3+7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
