name: camera_cor_destaque
description: Aplicativo que diz em voz alta o que a câmera está vendo.
publish_to: none
version: 2.0.0-dev+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.12.1
  flutter_tts: ^4.2.5
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/efficientdet_lite0.tflite
